openapi: 3.0.2
info:
  title: Tasks Creater
  description: Quick sample for reproducing an issue with Connexion
  termsOfService: http://no/terms/
  contact:
    email: no.need@gmail.com
  license:
    name: Copy, change, use - all yours
    url: http://all/yours
  version: 1.0.0
externalDocs:
  description: Got to get this fixed
  url: http://fix.please
servers:
- url: /api/v1
paths:
  /uploadfiles:
    post:
      tags:
      - uploadfiles
      summary: Upload multiple files
      operationId: controller.upload
      requestBody:
        description: Files that are uploaded
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  format: binary
      responses:
        200:
          description: All OK
