openapi: 3.0.2
info:
  title: Tasks Creater
  description: A tasks creation and dispatcher module
  termsOfService: http://no/terms/
  contact:
    email: ankur.vatsa@gmail.com
  license:
    name: GNU GPLv3
    url: https://github.com/vatsaaa/tasks/COPYING
  version: 1.0.0
externalDocs:
  description: Got to get this fixed
  url: http://fix.please
servers:
- url: /api/v1
paths:
  /ping:
    get:
      summary: Health check url
      operationId: controllers.controllers.ping
      parameters:
        - in: query
          name: suffix
          required: false
          schema:
            type: string
          description: suffix is appended to response from the service 
      tags:
      - Health Check
      responses:
        200:
          description: ping( ) services responds to user's ping with pong and the time at which the srvice was invoked. e.g. 
